# Generated by Django 6.0.2 on 2026-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('contribution_type', models.CharField(choices=[('shop', 'Shop'), ('service', 'Professional Service'), ('entertainment', 'Entertainment & Events'), ('education', 'Education / Training'), ('restauration', 'Restaurant / Food'), ('art-culture', 'Art & Culture'), ('health', 'Health & Wellness'), ('other', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
