# Generated by Django 6.0.2 on 2026-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_company_location_company_logo_url_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
