# Generated by Django 6.0.2 on 2026-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_company_logo_company_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
