# Generated by Django 6.0.2 on 2026-03-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_customer_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_company_favorite',
        ),
        migrations.AddField(
            model_name='favorite',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_favorites', to='users.company'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='company_follower',
        ),
    ]
