# Generated by Django 6.0.2 on 2026-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_dashboard_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
