# Generated by Django 6.0.2 on 2026-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_company_is_dashboard_active_delete_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_dashboard_active',
        ),
        migrations.AddField(
            model_name='company',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
