# Generated by Django 6.0.2 on 2026-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_company_created_at_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
