# Generated by Django 6.0.2 on 2026-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_company_last_activity_customer_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
