# Generated by Django 6.0.2 on 2026-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_activitylog_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvisit',
            name='visit_type',
            field=models.CharField(choices=[('profile_view', 'Profile View'), ('website_click', 'Website Click')], db_index=True, default='profile_view', max_length=20),
        ),
    ]
