# Generated by Django 6.0.2 on 2026-05-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_companyvisit_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website_3',
            field=models.URLField(blank=True),
        ),
    ]
