# Generated by Django 6.0.2 on 2026-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_company_website_2_company_website_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvisit',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='favorite',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
